apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      hostNetwork: true  # 继续使用宿主机网络方便实验
      containers:
      - name: nginx
        # 注意：这里换成你的 GitHub 镜像完整路径 (全小写)
        # 例如: ghcr.io/your-github-user/my-nginx-web:latest
        image: ghcr.io/zentrix566/my-nginx-web
        imagePullPolicy: Always # 关键：确保每次重启都重新拉取镜像